.build_template: &build_template
  stage: build
  tags:
    - build
  image: ${IMAGE}
  variables:
    # Enable ccache for all build jobs. See configure_ci_environment.sh for more ccache related settings.
    IDF_CCACHE_ENABLE: "1"
    BATCH_BUILD: "1"
    V: "0"
    WARNING_STR: ""

.build_examples_template: &build_examples_template
  <<: *build_template
  artifacts:
    when: always
    paths:
      - "**/build*/size.json"
      - "**/build*/build_log.txt"
      - "**/build*/*.bin"
      # upload to s3 server to save the artifacts size
      - "**/build*/*.map"
      - "**/build*/*.elf"
      - "**/build*/flasher_args.json"
      - "**/build*/flash_project_args"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/bootloader/*.elf"
      - "**/build*/partition_table/*.bin"
      - size_info.txt
    expire_in: 1 week
  variables:
    IDF_CI_BUILD: "1"
      # By configuring this macro, you can append the compiled configuration file.
    # For example, using "sdkconf.etc=default" specifies the default sdkconfig file.
    EXAMPLE_CONFIG: "="
  script:
    - pip install --upgrade idf-component-manager
    - pip install "idf_build_apps<2.0"
    - python tools/build_apps.py ${EXAMPLE_DIR} --config ${EXAMPLE_CONFIG} -t esp32s3 -vv

.build_matter_template: &build_matter_template
  before_script:
    - . ${ESP_MATTER_PATH}/export.sh

build_example_matter_switch:
  extends:
    - .build_matter_template
    - .build_examples_template
    - .rules:build:example_matter_switch
  image: espressif/esp-matter:latest_idf_v5.1.1
  variables:
    EXAMPLE_DIR: examples/matter_switch

build_example_chatgpt_demo:
  extends:
    - .build_examples_template
    - .rules:build:example_chatgpt_demo
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_DIR: examples/chatgpt_demo
    NVS_DIR: examples/chatgpt_demo/factory_nvs
  before_script:
    - pwd
    - mkdir ${NVS_DIR}/build
    - touch ${NVS_DIR}/build/factory_nvs.bin

build_example_chatgpt_demo_factory_nvs:
  extends:
    - .build_examples_template
    - .rules:build:example_chatgpt_demo_factory_nvs
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_DIR: examples/chatgpt_demo/factory_nvs

build_example_factory_demo:
  extends:
    - .build_examples_template
    - .rules:build:example_factory_demo
  parallel:
    matrix:
      #- IMAGE: espressif/idf:release-v5.0 don't support release-v5.0 now.
      - IMAGE: espressif/idf:release-v5.1
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_DIR: examples/factory_demo

build_example_image_display:
  extends:
    - .build_examples_template
    - .rules:build:example_image_display
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_DIR: examples/image_display

build_example_lv_demos:
  extends:
    - .build_examples_template
    - .rules:build:example_lv_demos
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_DIR: examples/lv_demos

build_example_mp3_demo:
  extends:
    - .build_examples_template
    - .rules:build:example_mp3_demo
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_DIR: examples/mp3_demo

build_example_usb_camera_lcd_display:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_camera_lcd_display
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_DIR: examples/usb_camera_lcd_display

build_example_esp_joystick:
  extends:
    - .build_examples_template
    - .rules:build:example_esp_joystick
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.1
  variables:
    EXAMPLE_DIR: examples/esp_joystick

build_example_usb_headset:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_headset
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.2
      - IMAGE: espressif/idf:release-v5.1
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_DIR: examples/usb_headset

build_example_watering_demo:
  extends:
    - .build_examples_template
    - .rules:build:example_watering_demo
  parallel:
    matrix:
      - IMAGE: espressif/idf:release-v5.0
      - IMAGE: espressif/idf:release-v5.1
      - IMAGE: espressif/idf:latest
  variables:
    EXAMPLE_DIR: examples/watering_demo
